name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.0.0'
          bundler-cache: true
      - run: bundle exec rake

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: fastlane test